-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CIDADE (
NOME Texto(1),
PAIS Texto(1),
ESTADO Texto(1),
ID_CID Texto(1) PRIMARY KEY
)

CREATE TABLE BAIRRO (
NOME Texto(1),
ID_BAI Texto(1) PRIMARY KEY,
ID_CID Texto(1),
FOREIGN KEY(ID_CID) REFERENCES CIDADE (ID_CID)
)

CREATE TABLE ENDERECO (
TIPOLOG Texto(1),
ID_END Texto(1) PRIMARY KEY,
LOGRADOURO Texto(1),
NUMERO Texto(1),
CEP Texto(1),
COMPLEMENTO Texto(1),
ID_BAI Texto(1),
ID_FUN Texto(1),
FOREIGN KEY(ID_BAI) REFERENCES BAIRRO (ID_BAI)
)

CREATE TABLE FUNCIONARIO (
NOME Texto(1),
CPF Texto(1),
RG Texto(1),
CARGO Texto(1),
ID_FUN Texto(1) PRIMARY KEY
)

CREATE TABLE VENDA (
DATA Texto(1),
FORMAPGMT Texto(1),
ID_VEN Texto(1) PRIMARY KEY,
ID_FUN Texto(1),
FOREIGN KEY(ID_FUN) REFERENCES FUNCIONARIO (ID_FUN)
)

CREATE TABLE GENERO (
NOME Texto(1),
ID_GEN Texto(1) PRIMARY KEY
)

CREATE TABLE FILME (
ID_FIL Texto(1) PRIMARY KEY,
NOME Texto(1),
VALOR Texto(1),
DESC Texto(1),
ID_GEN Texto(1),
FOREIGN KEY(ID_GEN) REFERENCES GENERO (ID_GEN)
)

CREATE TABLE SALA (
ID_SAL Texto(1) PRIMARY KEY,
DESC Texto(1),
CAPACIDADE Texto(1),
NUMERO Texto(1)
)

CREATE TABLE SESSAO (
ID_SES Texto(1) PRIMARY KEY,
HORARIO Texto(1),
OBS Texto(1),
Espectadores Texto(1),
ID_FIL Texto(1),
ID_SAL Texto(1),
FOREIGN KEY(ID_FIL) REFERENCES FILME (ID_FIL),
FOREIGN KEY(ID_SAL) REFERENCES SALA (ID_SAL)
)

CREATE TABLE TELEFONE (
NUMERO Texto(1),
CODAREA Texto(1),
RAMAL Texto(1),
DESC Texto(1),
ID_TEL Texto(1) PRIMARY KEY,
ID_FUN Texto(1),
FOREIGN KEY(ID_FUN) REFERENCES FUNCIONARIO (ID_FUN)
)

CREATE TABLE +VENDA_FILME (
ID_FIL Texto(1),
ID_VEN Texto(1),
QUANT Texto(1),
PRECOUNI Texto(1),
FOREIGN KEY(ID_FIL) REFERENCES FILME (ID_FIL),
FOREIGN KEY(ID_VEN) REFERENCES VENDA (ID_VEN)
)

ALTER TABLE ENDERECO ADD FOREIGN KEY(ID_FUN) REFERENCES FUNCIONARIO (ID_FUN)
